name: CI/CD Lightsail ASP.NET

# Se ejecuta en cada push a main
on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build & Publish
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build in Release
      run: dotnet build --configuration Release --no-restore /p:TreatWarningsAsErrors=false

    - name: Publish self-contained
      run: dotnet publish --configuration Release --framework net8.0 --runtime linux-x64 --output publish --no-self-contained /p:TreatWarningsAsErrors=false

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: publish
        path: publish/

  deploy:
    name: Deploy to Lightsail via SSH
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
    - name: Execute remote deploy commands
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.LIGHTSAIL_HOST }}
        username: ${{ secrets.LIGHTSAIL_USER }}
        key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
        port: 22
        script: |
          set -e
          cd /home/ubuntu/Organizacional
          git reset --hard origin/master
          git pull origin master
          echo "Limpiando carpeta publish anterior..."
          cd /home/ubuntu/Organizacional/publish
          # Borra todo menos wwwroot
          find . -mindepth 1 -maxdepth 1 ! -name 'wwwroot' -exec rm -rf {} +
          # Si existe wwwroot, borra todo menos uploads
          if [ -d ./wwwroot ]; then
            find ./wwwroot -mindepth 1 -maxdepth 1 ! -name 'uploads' -exec rm -rf {} +
          fi
          echo "Publicando app..."
          cd /home/ubuntu/Organizacional
          dotnet publish ./Organizacional.csproj --configuration Release --output ./publish
          echo "Publicación completada"
          sudo systemctl restart organiza.service
          echo "Servicio reiniciado"
        timeout: "300s"
